cyberark/conjur-authn-k8s-client

pkg/authenticator/authenticator_error.go
resolves https://github.com/cyberark/conjur-authn-k8s-client/issues/2
=> authenticator error prints status code

pkg/secrets/conjur_secrets.go, pkg/secrets/conjur_secrets_test.go, pkg/secrets/kubernetes_secrets.go, pkg/secrets/kubernetes_secrets_test.go, pkg/secrets/secrets.go
Add UT tests to kubernetes_secrets, conjur_secrets 
Fix small errors the UT has found
run the following command `./bin/test`
=> Add UT tests

cmd/sidecar/main.go, pkg/authenticator/authenticator.go, pkg/authenticator/config/config.go, pkg/secrets/config/config.go, pkg/secrets/secrets.go, pkg/storage/access_token_file.go, pkg/storage/access_token_file_test.go, pkg/storage/access_token_memory.go, pkg/storage/access_token_memory_test.go, pkg/storage/config/config.go, pkg/storage/storage_handler.go
implement AccessToken interface and add UT
run the following command `./bin/test`
=> Impl access token

pkg/secrets/handlers/secrets_handler_k8s_test.go, pkg/secrets/k8s/k8s_secrets_test.go
fix unstable ut
- sort maps and slices before comparison
=> fix unstable ut

pkg/secrets/config/config.go, pkg/storage/storage_handler.go
fix bug K8S_SECRETS env is required in none mode
=> fix bug K8S_SECRETS env is required in none mode

pkg/access_token/access_token_file_test.go, pkg/access_token/access_token_memory_test.go, pkg/authenticator/authenticator_test.go, pkg/secrets/handlers/secrets_handler_k8s.go, pkg/secrets/handlers/secrets_handler_k8s_test.go, pkg/secrets/k8s/k8s_secrets_test.go
=> Add UTs to secrets handler

pkg/access_token/access_token_file_test.go, pkg/access_token/access_token_memory_test.go
This PR is an additional PR to #36 in order to refactor the UTs after the major push
=> Refactors UTs

Dockerfile, Dockerfile.junit, Dockerfile.test
We should change the maintainer in our Dockerfiles from `Conjur inc.` to `CyberArk Software Ltd.`
=> Change maintainer name to `CyberArk Software Ltd.` in Dockerfiles

CHANGELOG.md, pkg/authenticator/version.go
- Added ability for authn client to print its version upon startup (#93)
=> Bump to version 0.17.0

Dockerfile
This PR performs the following changes
  - Prevent running the container process as root (this is bad for
    security and requires extra work for that container to work in OCP)
  - Add ability to run the container without issues as a random UID
    which happens on all default deployments in OCP
=> Run the authenticator with a limited user

design/fips-compliance.md
Connected to #91 
MD file for easier review: https://github.com/cyberark/conjur-authn-k8s-client/blob/fips-design/design/fips-compliance.md
In this design I share my thoughts and suggested approach to making the authenticator client FIPS compliant.
In some cases I don't have a decision yet so I wrote `TBD`. In any case that you don't see `TBD` assume this is my final suggestion, and comment accordingly.
Please feel free to challenge every decision and comment if you think I am missing something.
=> Add solution design for FIPS compliance

design/fips-compliance.md
This PR adds the results of the performance test introduced in the solution design for making the authn-client FIPS-compliant.
=> Add performance tests results to solution design

design/authenticator-client-for-container-platforms.md
Since it may be useful to others who are interested in how this works, this PR adds a MD version of
the original design document (with minor updates to reflect actual implementation) to this repo.
=> Add original client design to project

README.md
Links to `cyberark/conjur-authn-k8s-client` DockerHub and RH registry image pages.
n/a
=> Update image registry links

CHANGELOG.md
This PR adds a missing tag link to the Changelog.
=> Add missing tag link in Changelog

Jenkinsfile
Updates pipeline to be auto-triggered to run daily.
n/a
=> Force pipeline to run daily

design/simple-client-configuration.md
Add the design doc for simpler client configuration. The design was approved on March 15, 2021.
See #226 for the epic related to the implementation of this design.
cyberark/conjur#2045
=> Add design for simpler client configuration

Jenkinsfile, bin/validate-schema, helm/kubernetes-cluster-prep/Chart.yaml, helm/kubernetes-cluster-prep/values.schema.json, helm/kubernetes-cluster-prep/values.yaml
- Adds values.schema.json, which is used by Helm to place validation rules on the values.yml file
- Adds bin/validate-schema, which verifies that the values.schema.json is valid Json
- Adds json schema validation to jenkins pipeline
Resolves #233 
=> Add schema validation for helm chart

README.md
Rename Conjur OSS mentions to Conjur Open Source
- [] This PR does not require updating any documentation
=> Rename OSS to open source

README.md
By default, the authenticator client container runs with the built-in
defaults:
- Username: `authenticator`
- User ID:  `777`
- Group ID: `777`
For non-OpenShift platforms, it is possible to run a Pod that contains
the authenticator client container using an arbitrary, non-root user.
However, if this is configured incorrectly, the authenticator client
container will continually hang with file permissions errors when it
tries to read its client SSL certificate at /etc/conjur/ssl/*.
This change adds instructions to the README.md for running the
authenticator in a Kubernetes Pod using a non-default user and/or
group ID for *non-OpenShift* platforms.
For OpenShift platforms, this technique does not work because OpenShift
has strict requirements for fsGroup configuration used on Pods.
**NOTE: …
=> Adds instructions for running with non-default user on non-Openshift

helm/application-namespace-prep/test-schema, helm/common/utils.sh, helm/kubernetes-cluster-prep/test-schema
This fixes a test-schema error with a missing function name.
Also moves the common functions from the two test-schema functions to the common file.
=> Fixes test function name and move common functions

helm/kubernetes-cluster-prep/.helmignore, helm/kubernetes-cluster-prep/bin/get-conjur-cert.sh, helm/kubernetes-cluster-prep/templates/tests/_helm_test.bats.txt, helm/kubernetes-cluster-prep/templates/tests/_utils.sh.txt, helm/kubernetes-cluster-prep/templates/tests/test-cluster-prep-configmap.yaml, helm/kubernetes-cluster-prep/templates/tests/test-cluster-prep.yaml, helm/kubernetes-cluster-prep/test-helm, helm/kubernetes-cluster-prep/values.yaml
This adds the  Helm Test to kubernetes-cluster-prep
Resolves #229 
=> Adding Helm Test to kubernetes-cluster-prep

CHANGELOG.md, pkg/authenticator/version.go
This PR bumps the version to `0.20.0` for release.
=> Bump version to 0.20.0

helm/conjur-config-namespace-prep/Chart.yaml
Change namespace-prep chart version to 0.1.0 to match cluster-prep
=> Change namespace-prep chart version to 0.1.0

.github/workflows/e2e-workflow.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-init/values.schema.json, helm/conjur-app-deploy/charts/app-summon-sidecar/values.schema.json, helm/conjur-app-deploy/values.schema.json
Adds a json.schema.validation file to the Helm chart conjur-app-deploy
Resolves #265
=> Add json.schema.validation file

.github/workflows/helm-tests.yaml, bin/test-workflow/2_admin_load_conjur_policies.sh, bin/test-workflow/policy/templates/cluster-authn-svc-def.template.yml, bin/test-workflow/utils.sh, bin/validate-helm, helm/conjur-config-cluster-prep/templates/NOTES.txt, helm/conjur-config-namespace-prep/templates/NOTES.txt, helm/conjur-config-namespace-prep/templates/conjur_connect_configmap.yaml, helm/conjur-config-namespace-prep/templates/tests/_authn_container.yaml.txt, helm/conjur-config-namespace-prep/templates/tests/_helm_test.bats.txt, helm/conjur-config-namespace-prep/templates/tests/_utils.sh.txt, helm/conjur-config-namespace-prep/templates/tests/test-namespace-prep-configmap.yaml, helm/conjur-config-namespace-prep/templates/tests/test-namespace-prep.yaml, helm/conjur-config-namespace-prep/test-helm, helm/conjur-config-namespace-prep/values.yaml
This change adds support for running Helm test validation on the application
Namespace prep Helm chart via GitHub actions.
Since the installation of the Namespace prep Helm chart requires a "Golden"
ConfigMap, the Helm this test also includes the prerequisite Helm install of
the Kubernetes cluster prep Helm chart before the Namespace prep chart
install.
The Namespace prep Helm chart tests include 4 scenarios:
- "Happy" path
- Incorrect Conjur URL configuration
- Incorrect Conjur certificate configuration
- Incorrect authenticator ID configuration
For the scenarios where errors are expected, the test also confirms that
the Helm test correctly reports the expected test case failure in its
output.
This change also includes the addition of a second validator host ID to the
Conjur policy that …
=> Adds Helm validation tests for application Namespace prep Helm chart

helm/conjur-config-cluster-prep/templates/clusterrole.yaml, helm/conjur-config-cluster-prep/templates/golden_configmap.yaml, helm/conjur-config-cluster-prep/templates/serviceaccount.yaml, helm/conjur-config-namespace-prep/templates/authenticator_rolebinding.yaml, helm/conjur-config-namespace-prep/templates/conjur_connect_configmap.yaml
Add a descriptive YAML comment to each K8S resource created by the cluster-prep and namespace-prep Helm charts such that they appear in the autogenerated raw manifests.
Resolves #353
=> Yaml comments for K8s resources 

bin/test-workflow/0_prep_env.sh, bin/test-workflow/1_deploy_conjur.sh, bin/test-workflow/openshift/conjur-cli.yml, bin/test-workflow/openshift/test-curl.yml
This updates the the test-workflow scripts for Openshift.
Resolves #248 
=> Updates the test-workflow scripts for Openshift

Jenkinsfile
- A new Jenkins stage was added for testing against the `OCP_NEXT` cluster. This parameter is used by infra  via [openshift-next-suite-test](https://github.com/conjurinc/openshift-next-suite-test) to test our project suites against newly deployed OCP clusters (OCP_NEXT). 4.9 is on the roadmap soon, and this is the last of the projects listed in PR [openshift-next-suite-test](https://github.com/conjurinc/openshift-next-suite-test/pull/2) that needs to support this parameter
- This stage was added in serial (not parallel) as running two stages in parallel in OCP will influence both stages at runtime, which introduces flakiness
- Verify that all CI test …
=> Add OCP Next support in Jenkins

pkg/authenticator/config/configuration_factory.go
ONYX-15368: Add NewConfigFromCustomEnv
To support bump on secrets provider
=> ONYX-15368: Add NewConfigFromCustomEnv

.gitignore, .idea/runConfigurations/Debug_Authn_K8S_Client_On_Pod.xml
Update .gitignore to exclude IntelliJ files
=> Update .gitignore to exclude IntelliJ files

pkg/authenticator/jwt/tests/authenticator_test.go
Added UT for empty JWT token path
ONYX-15245
merged.*
changes, or
=> ONYX-15245: Added UT for Empty token path

cmd/authenticator/main.go, go.mod, go.sum, pkg/authenticator/jwt/authenticator.go, pkg/authenticator/k8s/authenticator.go
The 'trace' package has migrated from secrets-provider to it's own repo. This PR updates the references to it.
- Update references to 'trace' package
N/A
merged.*
changes, or
=> Use new "conjur-opentelemetry-tracer"

bin/test-workflow/7_app_deploy.sh, bin/test-workflow/8_app_verify_authentication.sh, bin/test-workflow/policy/app-policy.yml, bin/test-workflow/policy/load_policies.sh, bin/test-workflow/policy/templates/app-grants.template.yml, bin/test-workflow/policy/templates/app-identities-policy-jwt.template.yml, bin/test-workflow/start, helm/conjur-app-deploy/Chart.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/Chart.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/README.md, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/templates/NOTES.txt, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/templates/rbac.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/templates/test_app_secrets_provider_p2f.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/values.schema.json, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/values.yaml, helm/conjur-app-deploy/values.yaml
Add automation for push2f with authn jwt
Command:
./bin/test-workflow/start -n -a secrets-provider-p2f-jwt --jwt
Ticket : ONYX-16318
=> ONYX-16318: Add automation for secrets provider p2f authn jwt

helm/conjur-config-namespace-prep/README.md
The document links should point to the correct pages.
Updated the  Helm template links, and removed a doc link that was no longer valid.
merged.*
changes, or
=> Update the conjur-config-namespace-prep README links

Dockerfile, Dockerfile.test, Jenkinsfile, go.mod
- Added Jenkins library function to propogate go.mod with upstream dependencies
- Subsequent pipeline stages no longer have to get these dependencies independently
Ensure that the go.mod file matches the source code in the module and
contains the latest version of dependencies. This will allow successive
CI stages to have the necessary module requirements to run.
The go.mod file contains the latest upstream dependencies that the project requires.
A Jenkins library function has been created to map the repos source code and
execute go mod tidy in order to load all of the necessary packages.
changes, or
=> Automated Release Fix

bin/build, bin/build_utils, bin/publish
- Fix local builds of images
- Fix docker image promotion
- Generate VERSION for local builds if VERSION file doesn't exist
- Prepend internal registry to local docker images during release promotion
- Remove unnecessary echo statement
=> Check if local version file exists

CHANGELOG.md, bin/test-workflow/test_app_summon/Dockerfile.builder
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Update Dockerfile.builder to use a newer base image. 
merged.*
changes, or
=> Update test_app_summon Dockerfile.builder base image

helm/conjur-config-namespace-prep/README.md
Noticed some mistakes in the `Configuration` table of the Namespace Prep Helm chart documentation.
Updated Namespace Prep documentation to accurately represent configuration options and defaults.
N/A
merged.*
changes, or
=> Fix Configuration table in Namespace Prep README

Jenkinsfile
Update reference for test image reference used for promotion.
- Update reference to properly pull test image
- Successful promotion from branch has occured, so results are verified
changes, or
=> Fix test image name and local tag

CHANGELOG.md
Updates changelog entry to include the newer version to use for changes.
=> Add next version entry

NOTICES.txt, helm/conjur-app-deploy/Chart.yaml
Update versions in preparation for a release to address yaml.v3 dependencies as much as we can.
- Added NOTICES.txt entry for go.opentelemetry.io/otel & Apache 2.0 license
- Updated conjur-app-deploy helm chart version to reflect the new(ish) subchart to test secret rotation per @john-odonnell.
CyberArk internal issue: CONJSE-1378
merged.*
changes, or
=> Bump version for yaml.v3 fix release

helm/conjur-app-deploy/Chart.yaml, helm/conjur-config-cluster-prep/Chart.yaml, helm/conjur-config-cluster-prep/generated/conjur-config-cluster-prep.yaml
Updates Helm Chart versions to align with new namespace label-based authentication implementation.
https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-25808
=> Bump version to 0.23.8

bin/test-workflow/0_prep_env.sh, bin/test-workflow/1_deploy_conjur.sh, bin/test-workflow/4_admin_cluster_prep.sh, bin/test-workflow/5_app_namespace_prep.sh, bin/test-workflow/6_app_deploy_backend.sh, bin/test-workflow/7_app_deploy.sh, bin/test-workflow/8_app_verify_authentication.sh, bin/test-workflow/policy/app-policy.yml, bin/test-workflow/policy/load_policies.sh, bin/test-workflow/policy/templates/app-grants.template.yml, bin/test-workflow/policy/templates/app-identities-policy.template.yml, bin/test-workflow/start, bin/test-workflow/utils.sh, helm/conjur-app-deploy/Chart.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/Chart.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/README.md, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/templates/NOTES.txt, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/templates/rbac.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/templates/test_app_secrets_provider_p2f_injected.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/test-schema, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/test-unit, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/tests/test_app_secrets_provider_p2f_injected_test.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/values.schema.json, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/values.yaml, helm/conjur-app-deploy/values.yaml
E2E tests should include a test using the sidecar injector
Updated the E2E helm charts to include the sidecar injector and added an injected test case.
merged.*
changes, or
=> Updating E2E tests with sidecar injector and adding an injected test

CHANGELOG.md, helm/conjur-app-deploy/Chart.yaml, helm/conjur-config-cluster-prep/Chart.yaml, helm/conjur-config-cluster-prep/generated/conjur-config-cluster-prep.yaml
Prep to release v0.24.0
Bump helm chart versions, add missing changelog entry
merged.*
changes, or
=> Bump version to 0.24.0

bin/publish
=> Escape summon variable in Red Hat registry login

bin/publish
Fix CI issue introduced while debugging Red Hat pushing
merged.*
changes, or
=> Revert 'escape summon variable' change

CHANGELOG.md
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
- _Are there relevant screenshots you can add to the PR description?_
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or
=> Add empty Changelog section

CHANGELOG.md, Dockerfile, Dockerfile.helm-unit-test, Dockerfile.junit, Dockerfile.test, dev/Dockerfile.debug, go.mod, go.sum
Address Snyk vulnerabilities
Updated base image versions and golang.org/x/net
merged.*
changes, or
=> Address Snyk vulnerabilities

CHANGELOG.md, helm/conjur-app-deploy/charts/app-secretless-broker/templates/test_app_secretless_broker.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-k8s-jwt/templates/test_app_secrets_provider_k8s.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/templates/test_app_secrets_provider_p2f_injected.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f/templates/test_app_secrets_provider_p2f.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-rotation/templates/test_app_secrets_provider_rotation.yaml, helm/conjur-app-deploy/charts/app-summon-sidecar/templates/test-app-summon-sidecar.yaml
Container manifests should not have Snyk issues.
Updated the container security settings.
Not all Snyk issues can be addressed as these are manifests for CI and require some of the setting.
Other settings line liveness probes are not needed for CI.
The other Synk issues were addressed in PR [516](https://github.com/cyberark/conjur-authn-k8s-client/pull/516)
CyberArk internal issue ID: CONJSE-1745
merged.*
changes, or
=> Update container security settings

CHANGELOG.md, Dockerfile, Jenkinsfile, bin/test-workflow/1_deploy_conjur.sh
Updating the RH base image fixes the mismatch between libc versions with the authenticator-client-builder image
For context 
```bash
$ docker run --rm -it --entrypoint=  golang:1.20 ldd --version ldd   # builder image
ldd (Debian GLIBC 2.36-9) 2.36
...
$ docker run --rm -it --entrypoint=  registry.access.redhat.com/ubi8/ubi  ldd --version ldd # previous redhat base image 
ldd (GNU libc) 2.28
...
$ docker run --rm -it --entrypoint=  registry.access.redhat.com/ubi9/ubi  ldd --version ldd # updated redhat base image
ldd (GNU libc) 2.34
...
```
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
- _Are there …
=> Fix:  Update RH base image to ubi9/ubi 

CHANGELOG.md, helm/conjur-app-deploy/charts/app-secretless-broker-jwt/templates/test_app_secretless_broker.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-k8s-jwt/templates/test_app_secrets_provider_k8s.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-injected/templates/test_app_secrets_provider_p2f_injected.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/templates/test_app_secrets_provider_p2f.yaml, helm/conjur-app-deploy/charts/app-secrets-provider-p2f/templates/test_app_secrets_provider_p2f.yaml, helm/conjur-app-deploy/charts/app-summon-sidecar-jwt/templates/test-app-summon-sidecar.yaml
This pull request addresses the Snyk vulnerabilities outlined in this repository.
Addresses the lint issues in the YAML files included in this repository.
changes, or
=> Address Snyk issues

Jenkinsfile
Enable 'Enterprise in Jenkins' pipeline stages
This reverts commit 0bcf7a1be3d28ded1e1634541e356f2647d9a955.
N/A
merged.*
changes, or
=> Enable 'Enterprise in Jenkins' pipeline stages

CHANGELOG.md
*Please describe the desired outcome for this PR.  Said another way, what was
the original request that resulted in these code changes?  Feel free to copy
this information from the connected issue.*
*Describe how the desired outcome above has been achieved with this PR. In
particular, consider:*
- _Are there relevant screenshots you can add to the PR description?_
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or
=> Add empty v0.26.1 Changelog entry
