- pkg/authenticator/authenticator.go
- pkg/authenticator/requests.go
We had been sending the client cert in the header and in the body for v5 Conjur.
This commit updates it to no longer send the cert in the request body.
I have verified that this works by deploying Conjur 5.2.2 patched with `conjur-possum_1.3.1.12-177c34d_amd64.deb` to GKE using `kubernetes-conjur-deploy` and then running `kubernetes-conjur-demo` using a build of this branch of the k8s authenticator.
To test yourself:
- Deploy any recent build of Conjur to GKE using `kubernetes-conjur-deploy`
- Build this branch of the authenticator client locally by running `./bin/build`
- Deploy the demo apps by running the version of the demo [in my related PR](https://github.com/conjurdemos/kubernetes-conjur-demo/pull/31/) with `LOCAL_AUTHENTICATOR=true` in your environment
> No longer send client cert in authenticate request

- go.mod
- go.sum
Fixes a bug with parsing pk7 encrypted tokens by updating gomod to use latest commit from master branch of `fullsailor/pkcs7`
> fix: use latest commit of fullsailor/pkcs7

- CHANGELOG.md
Paths in the changelog were copy/pasted from a different project
without changes so this fixes the problem
> Fix changelog link paths

- pkg/secrets/secrets.go
Fixed secrets update
- Parse the variable ID to ommit the `account:variable:` prefix
- Pass the PathMap to the `K8sSecretsMap` object
> Fixed secrets update

- pkg/storage/access_token_file_test.go
- pkg/storage/access_token_memory_test.go
Add UT tests for delete interface 
- Both arrays as input to write(data []byte) and output from read() should be cleared from memory after delete()
> Add UT tests for AccessToken delete interface

- pkg/storage/storage_handler.go
We should exit the program only in `main.go` to better handle errors. This PR returns `nil` to main in every place we exited explicitly outside of main
> Exit program only in main

- pkg/secrets/handlers/secrets_handler_k8s.go
- pkg/secrets/handlers/secrets_handler_k8s_test.go
- pkg/secrets/k8s/k8s_secrets.go
We had a bug where if more than 1 k8s secret were mapped to a single conjur secret we updated only one of them. This commit fixes that
> Allow more than 1 k8s secret to map to a single Conjur secret

- CHANGELOG.md
NewFromEnv method does not take input parameters anymore and is using default values for `tokenFilePath` & `clientCertPath`. This PR adds a note about this to the CHANGELOG. 
We changed this in 0.14.0 so it is added under that section in the CHANGELOG.
This change happened as part of [this PR](https://github.com/cyberark/conjur-authn-k8s-client/pull/40)
> Add note in CHANGELOG for NewFromEnv signature change

- pkg/authenticator/config/username.go
- pkg/authenticator/config/username_test.go
Connected to cyberark/conjur#1260
Prior to this commit, we assumed that the application identity of the
host was defined in the host id, with a 3-part suffix. Now that the
Conjur server accepts authentication of hosts that have their
application identity defined in annotations, we need to modify the
client to remove the restriction on the host id. Additionally, this
commit changed the suffix from having the last 3 parts of the id to have
the actual id, while the prefix has the policy id.
To maintain backwards compatibility with an old Conjur server, we need
to support a suffix that includes the 3-part application identity (and
as mentioned earlier, the suffix should include the host-id which in
this case is the 3-part application identity). In such a case, we take
the last 3 parts of the …
> Authenticate hosts without application identity in the id

- bin/build_utils
- bin/publish
Used https://github.com/cyberark/secretless-broker/commit/56462fbfb64f89900d3ccd8a707e5a5b1273a6e1#diff-66a2901e5a92803e08f503c72520e8a8 as a reference.
Updated `publish` file to only push to Docker Hub if the tag matches `VERSION`. Used an old Secretless commit as a reference. Tested locally, but haven't been able to test to make sure it actually pushes to Docker Hub. 
Issue: https://github.com/cyberark/conjur-authn-k8s-client/issues/69
> Update publish to only push to Docker Hub on new version

- bin/publish
Update to only push to RedHat container registry when the tag matches the version
We suspect RedHat will fail the push when there is already an image with the same tag, but
it's still better to avoid overwriting the original image (pushed when the tag was originally added)
with another image n commits past the tag.
> Only push to redhat when tag matches version

- Jenkinsfile
- bin/publish
- secrets.yml
Redhat's scan registry uses paths to separate projects and each
project has a different API key to use.  Now that there are multiple
projects, executor-wide login for the registry no longer works and
each build needs to do the corresponding login.
> Update to log into RedHat registry with project API key

- pkg/authenticator/config/config.go
- pkg/authenticator/config/config_test.go
When building a configuration from the environment, we now verify
that the input value for the Conjur version is '4' or '5'. If empty,
it will use a default value of '5'. If any other value is provided, we
throw an error.
- Performed a minor refactoring of NewFromEnv to allow functional options as arguments
- Created unit tests for conjur versions, with a framework which allows for additional unit tests for any of the features in config.go
> Default CONJUR_VERSION behavior refactored and tested

- bin/publish
In a previous [commit](https://github.com/cyberark/conjur-authn-k8s-client/commit/19ceb52df6987f4f98049b0238640b4f69e63610) we stopped publishing our image to the internal registry. However, the TAG variable was left behind for no reason.
It was used in the script as an intermediate name for the image but it is not needed and makes the script less readable.
> Remove redundant TAG variable from publish script

- bin/publish
There was an incorrect logic where we pushed the `latest` tag twice -
once when the `for` loop was with `tag == $VERSION` and once when the
`for` loop was with `tag == latest`.
Also - renaming `IMAGES` to `DESTINATION_IMAGES` for clarity
> Remove doubled push of `latest` tag

- CHANGELOG.md
This PR improves 2 changelog entries that now are:
- More accurate
- State customer facing changes instead of implementation details
> Improve changelog entries

- Jenkinsfile
Adds parallel trivy scanning - one for only potential vulns with fixes available and one for all detected potential vulns. Build failures occur only on potential vulns with fixes. Because this currently has no fixable potential vulns, I bumped the threshold to HIGH so we'll get build failures if new HIGH or CRITICAL potential vulnerabilities are discovered. 
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
> Builds fail only on fixable HIGH & CRITICAL vulns

- CHANGELOG.md
- Dockerfile
Connected to #91 
We want to let customers who require that the binary is built using
FIPS-compliant libraries an image of the conjur-authn-k8s-client.
This commit changes the base image from `golang` to `goboring/golang` and makes the required changes for it to work.
The image names stay the same as before.
It's important to state that the performance of the FIPS-compliant version is the same as the original one, as can be seen [here](https://github.com/cyberark/conjur-authn-k8s-client/pull/112).
> Build and publish a FIPS compliant image of conjur-authn-k8s-client

- CHANGELOG.md
The CHANGELOG entry regarding the FIPS compliancy change was entered
by accident to the `0.17.0` version section but it is not released yet.
> Move FIPS entry to Unreleased section in CHANGELOG

- CHANGELOG.md
In issue #111 we changed the authenticator-client to run with a limited
user instead of root but didn't add a changelog entry for it.
> Add changelog entry for issue #111

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CONTRIBUTING.md
- NOTICES.txt
- pkg/authenticator/version.go
This PR bumps the version to v0.18.0 and makes some final tweaks to the CHANGELOG to revise the messages and link to issues
It also adds a PR template and a NOTICES file to the project.
> Bump version to 0.18.0

- Jenkinsfile
We changed the base image of the authenticator client from `scratch`
to `alpine` to run with a limited user in the Docker image, instead of
the root user.
This change enables us to scan the image as we can determine now the OS.
Implementation option - we could also have this code instead:
```
script {
def tasks = [:]
["conjur-authn-k8s-client", "conjur-authn-k8s-client-redhat"].each { image ->
tasks["Scan {image} for fixable vulns"] = {
scanAndReport("{image}:dev", "HIGH", false)
}
tasks["Scan {image} for total vulns"] = {
scanAndReport("{image}:dev", "NONE", true)
}
}
parallel tasks
}
```
but i think that the suggested code is better as it's more readable and the duplication is not too strong. Let me know if you think otherwise.
> Scan also main image as it's now based on alpine

- Dockerfile
The Dockerfile was inconsistent in terms of how they name the MAINTAINER. This PR updates the MAINTAINER to `CyberArk Software Ltd.` because this is how we reference ourselves in the [official site](https://www.cyberark.com/)
> Update Dockerfile MAINTAINER to CyberArk Software Ltd.

- CHANGELOG.md
- cmd/authenticator/main.go
Connected to #158 
Prior to this commit, we hit the reset button on the expBackoff clock
before waiting the token refresh timeout. This means that the next
interval will start 6 minutes (by default) into the clock and only one
cycle will run (as we exceed the max elapsed time of 2 minutes).
Resetting the clock after the timeout waits ensures that the next cycle
will run for at most 2 minutes as intended.
Here is a log that shows the failure, in which we run only once before crashing (logs are written from bottom to top):
```
{"log":"ERROR: 2020/09/07 07:58:57 main.go:76: CAKC031E Retransmission backoff exhausted\n","stream":"stderr","time":"2020-09-07T07:58:57.784828076Z"}
{"log":"ERROR: 2020/09/07 07:58:57 main.go:48: CAKC016E Failed to …
```
> Reset expBackoff after we wait for TokenRefreshTimeout

- README.md
- pkg/authenticator/config/config.go
- pkg/log/log_messages.go
- pkg/utils/environment_variable.go
- pkg/utils/environment_variable_test.go
We would like to better UT the logic of reading a value from the env
and defaulting to a default value if it's not present. We also have the
logic that transforms this env var value into an int or a duration (and
maybe more in the future) and it is best that this logic is UTed and is
implemented in its own util. This improves the readability of the
config.go file and of the util functions themselves.
This will also let us use these utils in other projects that consume the
authn-client without implementing them there as well.
> Extract env var value read into a util

- CHANGELOG.md
- pkg/authenticator/version.go
- Logs now correctly print only the Conjur identity without the policy branch prefix.
([cyberark/conjur-authn-k8s-client#126](https://github.com/cyberark/conjur-authn-k8s-client/issues/126))
- When authentication fails, the exponential backoff retry is correctly reset so
that it will continue to attempt to authenticate until backoff is exhausted.
([cyberark/conjur-authn-k8s-client#158](https://github.com/cyberark/conjur-authn-k8s-client/issues/158))
- Wait slightly for the client certificate file to exist after login before
raising an error.
[cyberark/conjur-authn-k8s-client#119](https://github.com/cyberark/conjur-authn-k8s-client/issues/119)
> Bump version to 0.18.1

- CONTRIBUTING.md
The instruction for releasing a new RH image was duplicated.
> Remove duplication of RH image instructions

- CHANGELOG.md
- cmd/authenticator/main.go
- pkg/authenticator/authenticator.go
- pkg/authenticator/client.go
- pkg/authenticator/config/config.go
- pkg/authenticator/requests.go
- pkg/log/log_messages.go
- pkg/log/logger.go
- pkg/utils/environment_variable.go
- pkg/utils/file.go
Enhance logger with the following abilities:
1. Log levels (DEBUG, INFO, WARN, ERROR).
This allows better understanding of the logs, and writing logs in more
precise level.
2. Debug mode that allows turning DEBUG log level on and off.
This allows adding detailed logs that will not be written in production, but
can be added for investigation.
3. Add microseconds to logs timestamp.
Since authn client operation can be finished in less than a second, logs
time resolution of seconds is not enough to understand steps duration.
Connected to #164
Example of the logs after the change:
```
INFO:  2020/09/15 08:50:21.682962 main.go:16: CAKC014I Kubernetes Authenticator Client v0.18.1-aa8a2bc starting up...
INFO:  2020/09/15 08:50:21.743570 main.go:41: CAKC006I Authenticating as user …
```
> Enhance logger with log levels, debug mode and microseconds resolution

- .github/CODEOWNERS
Updates CODEOWNERS from @cyberark/conjur-core-team to @cyberark/community-and-integrations-team and @cyberark/palmtree, since the latter two groups are in practice the primary maintainers of this content.
n/a
> Change CODEOWNERS to PalmTree / C&I teams

- CHANGELOG.md
- go.mod
- go.sum
- pkg/authenticator/version.go
- pkg/log/logger_test.go
- Bumps version to 0.19.0
- We bump the MINOR version as the changes in this version do not make incompatible API changes and add functionality in a 
backwards compatible manner.
- Removes an unnecessary dependency
> Bump 0.19.0

- cmd/authenticator/main.go
- pkg/authenticator/authenticator.go
Some log messages should be part of the authentication methods so that
they are shown also when other projects consume the authn library.
For example, the secrets-provider calls the method `authn.Authenticate()`.
in the current implementation, we will not log the message
`Authenticating as user '%s'` as it's written in the backoff loop which
is not consumed in the secrets provider. Moving these messages into the
methods will let the consuming projects have them.
> Move authentication logs from backoff to auth methods

- CHANGELOG.md
- cmd/authenticator/main.go
- pkg/authenticator/authenticator.go
- pkg/authenticator/requests.go
Consumers of the authn-client library currently need to first call the
`Authenticate` method, get the output and call the method
`ParseAuthenticationResponse` with it. This adds redundant complexity
to the flow and can be reduced easily by letting the `Authenticate`
method perform the whole flow by itself. The impact can be seen in
`main.go` (and will affect other consumers such as the secrets-provider
and secretless).
Note that if we perform this change we will need to bump the MAJOR version as this breaks compatibility of the library.
> Perform all authentication flow in Authenticate

- .trivyignore
- CHANGELOG.md
- Dockerfile
- Dockerfile.junit
- Dockerfile.test
- go.mod
- pkg/utils/environment_variable_test.go
Bumps the Go version used in the project to v1.15.
Resolves #206 
> Update Go version to 1.15

- CHANGELOG.md
- CONTRIBUTING.md
- pkg/authenticator/version.go
Bumping version to 0.19.1.
Resolves #210 
> Bump version to 0.19.1

- pkg/authenticator/authenticator.go
- pkg/utils/file.go
- pkg/utils/file_test.go
fileutils is an internal detail. This also allows us to maintain the interfaces of WaitForFile and VerifyFileExists
>  Refactor to hide fileutils from the world

- helm/common/utils.sh
- helm/kubernetes-cluster-prep/test-schema
- helm/kubernetes-cluster-prep/test-unit
- helm/kubernetes-cluster-prep/tests/clusterrole_test.yaml
- helm/kubernetes-cluster-prep/tests/golden_configmap_test.yaml
- helm/kubernetes-cluster-prep/tests/serviceaccount_test.yaml
- helm/kubernetes-cluster-prep/values.schema.json
This change adds the following:
- Helm unit tests that use the `helm-unittest' Helm plugin for testing chart logic.
- Helm lint tests that tests the schema validation that is performed on chart values as defined in the `values.schema.json` file.
- Some fixes and added patterns for schema validation
Resolves #234
> Adds Helm UT and schema validity tests for cluster prep chart

- CHANGELOG.md
Adds OCP 4.6 support to changelog
Also moves the fix for #196 to the correct CL section
Resolves #262 
> Update changelog for OCP 4.6 support

- helm/kubernetes-cluster-prep/README.md
- helm/kubernetes-cluster-prep/bin/get-conjur-cert.sh
There are a few issues with the get-conjur-cert.sh that need to be fixed.
- When using the -f option if the path is relative, the file destination is relative
to the script directory, not the users directory.
- For the external case, it would be nice to check if openssl was installed to tell
the user why it's failing.
- Depending on the kubectl version, kubectl run might make a depoyment or pod,
it should always be deployment.
- Verify should work if there is a http:// prefix on the URL or not.
Fixes the above issues.
Resolves #278 
> Updating get-conjur-cert.sh

- helm/application-namespace-prep/.helmignore
- helm/application-namespace-prep/Chart.yaml
- helm/application-namespace-prep/NOTES.txt
- helm/application-namespace-prep/README.md
- helm/application-namespace-prep/templates/_helpers.tpl
- helm/application-namespace-prep/templates/authenticator-rolebinding.yml
- helm/application-namespace-prep/templates/conjur-connect-configmap.yml
- helm/application-namespace-prep/values.yaml
- helm/kubernetes-cluster-prep/values.schema.json
- helm/kubernetes-cluster-prep/values.yaml
- Adds namespace prep chart
- Adds rolebinding template
- Adds conjur connect configmap template
- Adds default values.yml
- Adds helper.tpl file with "helper" template models
Resolves #249 
> Add namespace prep chart

- Jenkinsfile
- helm/application-namespace-prep/values.schema.json
Adds json schema validation for the application namespace prep chart
Adds linting for the new json schema in the pipeline
Resolves #250 
> Add json schema validation for application namespace prep

- helm/application-namespace-prep/templates/authenticator-rolebinding.yml
- helm/application-namespace-prep/templates/conjur-connect-configmap.yml
- helm/application-namespace-prep/values.schema.json
Currently, when both required values are not provided, we see an
obscure nil interface{} pointer error:
```
Error: template: conjur-namespace-prep/templates/conjur-connect-configmap.yml:3:93: executing "conjur-namespace-prep/templates/conjur-connect-configmap.yml" at <.Values.authnK8s.name>: nil pointer evaluating interface {}.name
```
For this case, the error message should be clear that both required
values are needed:
```
Error: execution error at (conjur-namespace-prep/templates/conjur-connect-configmap.yml:3:15): Both authnK8s.namespace and authnK8s.configMap are required
```
Resolves #
> Fix error when both required vals missing for app-namespace-prep chart

- .gitignore
- CONTRIBUTING.md
- bin/test-workflow
- helm/app-deploy/Chart.yaml
- helm/app-deploy/README.md
- helm/app-deploy/charts/app-summon-sidecar/Chart.yaml
- helm/app-deploy/charts/app-summon-sidecar/README.md
- helm/app-deploy/charts/app-summon-sidecar/templates/NOTES.txt
- helm/app-deploy/charts/app-summon-sidecar/templates/conjur_authn_configmap.yaml
- helm/app-deploy/charts/app-summon-sidecar/templates/test-app-summon-sidecar.yml
- helm/app-deploy/charts/app-summon-sidecar/values.yaml
- helm/app-deploy/values.yaml
- helm/application-namespace-prep/values.yaml
- helm/kubernetes-cluster-prep/bin/get-conjur-cert.sh
- adds `bin/test-workflow` to run the conjur-oss helm demo, then run through the sequential installation process for our new helm charts. It "Just Works"™️
- Introduces the `app-test` charts, verifying functionality of our cluster and namespace prep charts.
- standardized default values across our namespace, cluster, and app charts, to allow for "out of the box" deployment
Resolves #238 
- [] This PR does not require updating any documentation
> Add App-Deploy charts 

- Dockerfile
- Jenkinsfile
- bin/build
- bin/build_utils
- bin/publish
This adds building and pushing the Helm test container to DockerHub.
The container will be pushed with the edge tag to get it in the repository before a build label is created.
This is split from the Helm test commit to get the image in place first so the helm test can be tested
against the new image.
Resolves #287 
> Adding the Heml test container to DockerHub

- Jenkinsfile
Jenkins is failing because the path to the publish script is wrong.
This updates the path.
> Fixes the path to the publish script.

- bin/publish
When Jenkins is running on master, getting an 
[2021-05-04T17:23:14.455Z] + summon ./bin/publish --edge
[2021-05-04T17:23:14.455Z] ./bin/publish: line 9: TAG_NAME: unbound variable
script returned exit code 1
This fixes the error by moving the --edge logic above the TAG_NAME
> Fixes an unbound variable error when using the edge tag

- Dockerfile.helm-test
- Jenkinsfile
- bin/test-helm
- bin/test-helm-in-docker
- helm/app-deploy/test-lint
- helm/application-namespace-prep/test-lint
- helm/application-namespace-prep/test-schema
- helm/application-namespace-prep/test-unit
- helm/common/utils.sh
- helm/kubernetes-cluster-prep/test-lint
- helm/kubernetes-cluster-prep/test-schema
- helm/kubernetes-cluster-prep/test-unit
Runs `helm lint` on kubernetes-cluster-prep, application-namespace-prep, and the sample-app helm charts as part of Jenkins pipeline. Done in a container because naturally the `helm` binary is needed. Also invokes the schema and unit tests for the kubernetes-cluster-prep and application-namespace-prep charts
Resolves #240 
> Add top level test script for linting helm charts and execute as part of CI

- helm/kubernetes-cluster-prep/README.md
- helm/kubernetes-cluster-prep/assets/example-conjur-policy-with-validator.yaml
- helm/kubernetes-cluster-prep/templates/tests/_authn_container.yaml.txt
- helm/kubernetes-cluster-prep/templates/tests/_helm_test.bats.txt
- helm/kubernetes-cluster-prep/templates/tests/test-cluster-prep.yaml
- helm/kubernetes-cluster-prep/test-helm
- helm/kubernetes-cluster-prep/values.yaml
This change adds an optional Helm chart test that can validate that a deployed Helm chart
release is actually capable of authenticating with the configured Conjur
instance. This Conjur authentication validation testing requires the
configuration of a special "validator" host ID in Conjur security policy
that supports Conjur Kubernetes authentication. This "validator" host ID
does not require access to Conjur secrets for the purposes of this
authentication test.
An example Conjur security policy that includes an "authenticate-only"
validator host ID for testing authentication can be found in
`assets/example-conjur-policy-with-validator.yaml`.
When the Conjur authentication validation test is enabled, the Helm test
Pod that is deployed for the `helm test ...` command will include an …
> Add Helm authentication validation test

- helm/kubernetes-cluster-prep/templates/tests/_helm_test.bats.txt
Adding checks for Conjur account and authenticatorID in the Helm tests.
This adds two Helm tests to validate the Conjur account and authenticatorID
that is retrieved from the /info endpoint.
The /info endpoint only works on the enterprise edition to extra checks were made
for the failing case if it wasn't enterprise.
Opted not to add new item to values.yaml
Instead of a setting of enterprise or oss, the test will parse the info endpoint.
If the data matches, it passes no matter what edition.
If the first test fails, then we do another check of the information gathered
from the curl of the endpoint. If it was oss, the results will not have lines
like account and name, it will just have "Authorization missing".
So for OSS, the tests will be skipped, as below.
```
ok 1 Conjur Appliance URL …
```
> Adding checks for Conjur account and authenticatorID

- Dockerfile
- helm/conjur-config-cluster-prep/templates/tests/_authn_container.yaml.txt
- helm/conjur-config-cluster-prep/templates/tests/_helm_test.bats.txt
The current Helm tests are always returning success for the Conjur
authentication validation test case. This change fixes this issue so
the the proper test result is reported.
Some other changes that are included:
- The validation tests for Conjur account and authenticator ID are changed
in the following ways:
- Test cases are skipped if the Conjur URL is not reachable
- Test cases check for authorization errors
- Test cases decode the YAML returned from the /info endpoint
using `yq` to ensure we're comparing against the proper info field.
- The checks for error codes in the authenticator logs are change in the
following ways:
- Error checks are not performed if authentication is successful
- New test case added for error code CAKC007
Resolves #312 
**If you are preparing for a release**, …
> Fixes false positives for Helm test authentication validation

- helm/conjur-config-cluster-prep/README.md
- helm/conjur-config-cluster-prep/bin/get-conjur-cert.sh
This add a fingerprint check to the get-conjur-cert script and asks
the user if they trust the cert. The user is asked to validate the fingerprint
by logging into the conjur server and getting the fingerprint there also.
The process for getting the fingerprint is longer in a Kubernetes
cluster, so in that case the script refers back to the README.
Works towards #297 
> Add fingerprint check in get-conjur-cert

- CHANGELOG.md
- Dockerfile
- Adds note to CHANGELOG about OCP 4.7 support
- Changes base image to `ubi8/ubi`
The `rhel7/rhel` base image we've been using has a [CVE](https://access.redhat.com/security/cve/cve-2021-27219) and no updated image in sight. 
n/a
> Update rh base image

- bin/test-workflow/QUICKSTART.md
Includes `bin/test-workflow/QUICKSTART.md`
Guide uses reusable scripts added in #307 
The quickstart guide will only improve with updates
addressing #322 and #323 - guide will be able to divide
steps more clearly by persona responsability.
Resolves #246 
> Add K8s Authenticator Quickstart

- Jenkinsfile
Currently, a conjur-authn-k8s-client image is not getting published
(pushed) to DockerHub when new Git tags have been added.
Example build log (for new tag v0.20.0):
https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur-authn-k8s-client/detail/v0.20.0/1/pipeline/156
The issue is that the Jenkinsfile is looking for not only a new tag (which is
correct), but also checking that the branch is `main` (which is incorrect...
the branch will be the version tag in this case, e.g. `v0.20.0`).
Also had to add a `--latest` argument in call to `bin/publish` because
this script is looking for `$1` positional parameter, and the
`bin/build_utils` script that it includes is setting the `-u` flag with `set -euo pipefail`.
Resolves #336
**If you are preparing for a release**, have you run …
> Fixes missing publish to DockerHub for new release tags

- .github/workflows/ci.yaml
- bin/validate-helm
- helm/conjur-config-cluster-prep/templates/tests/_helm_test.bats.txt
This adds a Helm release validation tests.
This script will create a Kind cluster, run the Helm cluster and namespace
prep Helm charts and run Helm tests.
There is also negative tests to validate the Helm tests fail as expected.
Resolves #241
> This adds a Helm release validation tests for the Helm charts.

- README.md
- bin/test-workflow/QUICKSTART.md
- design/authenticator-client-for-container-platforms.md
- design/simple-client-configuration.md
- design/templates/solution_design.md
- helm/conjur-config-cluster-prep/README.md
Updating naming for Conjur editions
- converts `Conjur OSS` to `Conjur Open Source`
- converts `DAP`/`Dynamic Access Provider` to `Conjur Enterprise`
- maintains `Conjur OSS Suite` and `Conjur Open Source Suite`
This is part of an automated batch of PRs across many repos listed in [cyberark/community#92](https://github.com/cyberark/community/issues/92)
> Updating naming for Conjur editions

- bin/test-workflow/7_app_deploy_backend.sh
- bin/test-workflow/policy/app-access.yml
- bin/test-workflow/policy/load_policies.sh
- bin/test-workflow/policy/templates/project-authn-def.template.yml
- helm/conjur-app-deploy/Chart.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/Chart.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/README.md
- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/NOTES.txt
- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/conjur_authn_configmap.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/rbac.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/secret.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/test_app_secrets_provider_init.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/values.yaml
- helm/conjur-app-deploy/values.yaml
A Helm subchart is added to the app deployment Helm chart for deploying an application + Secrets Provider init container.
* Helm values.yaml created for app subchart
* Helm manifest templates created for application + Secrets Provider sidecar
- ConfigMap (containing `conjur.authnLogin`),
- ServiceAccount
- Secret (updated by Secrets Provider)
- Role (get + update Secret)
- RoleBinding (bind ServiceAccount to Role)
* Helm chart successfully deploys (application + Secrets Provider init container)
* Helm chart includes a templates/NOTES.txt that announces app/authenticator has been deployed
* E2E workflow test scripts modified to:
- load Secrets Provider specific policies
- use a single test app backend for each authenticator type
Test steps:
* Run E2E workflow by executing …
> Add `secrets-provider-init` sample app Helm chart

- helm/README.md
- helm/conjur-config-cluster-prep/README.md
- helm/conjur-config-namespace-prep/README.md
- Added base README to `helm/` directory root with an overview of motivation and links to chart-specific READMEs
- Added sections highlighting which parts of Conjur Enterprise docs these charts are meant to supersede
- Added instructions for pregenerating k8s manifests with `helm template` to be applied with later with `kubectl`
- Added a section to the namespace Helm chart README that explains how to include the Conjur Connection ConfigMap values as environment variables in Pods deployed by application deployment manifests
Resolves #332
> Update Helm chart READMEs

- CHANGELOG.md
- pkg/authenticator/version.go
This PR bumps the version to `0.21.0` for release.
Resolves #261
Resolves #319
> Bump version to 0.21.0

- bin/test-workflow/0_prep_conjur_in_kind.sh
After a recent change ([PR # 154](https://github.com/cyberark/conjur-oss-helm-chart/pull/154)) to the Kubernetes-in-Docker example in the cyberark/conjur-oss-helm-chart repo, the GitHub actions tests that use the E2E workflow scripts started failing in CI.
The root cause is that the example scripts in the conjur-oss-helm-chart were reorganized to accommodate both a KinD example and an OpenShift example. So now the E2E workflow scripts are being modified to use the new script paths.
Resolves #356
> Fixes broken E2E workflow scripts

- bin/test-workflow/0_prep_env.sh
- bin/test-workflow/4_admin_cluster_prep.sh
- bin/test-workflow/5_app_namespace_prep.sh
- bin/test-workflow/cleanup_helm.sh
- bin/test-workflow/cleanup_namespaces.sh
- bin/test-workflow/stop
- bin/test-workflow/utils.sh
- Adds unique IDs to cluster and namespace prep helm charts
- Adds unique ID to cluster prep clusterrole
- In `stop` script, uses `helm uninstall` on cluster and namespace prep charts, to ensure all installed entities are removed
Doesn't close a ticket, but should resolve failing builds due to poor test teardown.
> Improve E2E test cleanup

- helm/conjur-config-namespace-prep/README.md
change authnK8s.NameSpace to authnK8s.namespace to match the correct helm values
- _Are there relevant screenshots you can add to the PR description?_
> Change authnK8s.NameSpace to authnK8s.namespace

- .github/workflows/helm-template-generate-k8s-manifests.yaml
- .github/workflows/release-upload-raw-k8s-manifests.yaml
- bin/helm-generate-raw-manifest-cluster-prep.sh
- bin/helm-generate-raw-manifest-namespace-prep.sh
- helm/conjur-config-cluster-prep/generated/conjur-config-cluster-prep.yaml
- helm/conjur-config-cluster-prep/sample-values.yaml
- helm/conjur-config-cluster-prep/templates/tests/test-cluster-prep-configmap.yaml
- helm/conjur-config-cluster-prep/templates/tests/test-cluster-prep.yaml
- helm/conjur-config-namespace-prep/generated/conjur-config-namespace-prep.yaml
- helm/conjur-config-namespace-prep/sample-values.yaml
- helm/conjur-config-namespace-prep/templates/authenticator_rolebinding.yaml
- helm/conjur-config-namespace-prep/templates/conjur_connect_configmap.yaml
- helm/conjur-config-namespace-prep/templates/tests/test-namespace-prep-configmap.yaml
- helm/conjur-config-namespace-prep/templates/tests/test-namespace-prep.yaml
Two new Github Actions added:
1) Auto-commit raw k8s manifests generated via `helm template` from `cluster-prep` and `namespace-prep` Helm charts
2) Upload raw manifests to tagged releases
Resolves #351 and #352
> Add GitHub Action which generates manifests from Helm charts

- bin/test-workflow/test_app_summon/Dockerfile
- bin/test-workflow/test_app_summon/Dockerfile.oc
- helm/conjur-config-cluster-prep/generated/conjur-config-cluster-prep.yaml
- helm/conjur-config-cluster-prep/templates/tests/test-cluster-prep-configmap.yaml
- helm/conjur-config-namespace-prep/generated/conjur-config-namespace-prep.yaml
- helm/conjur-config-namespace-prep/templates/tests/test-namespace-prep-configmap.yaml
- helm/conjur-config-namespace-prep/templates/tests/test-namespace-prep.yaml
The E2E workflow tests on KinD are currently failing after a recent
new release of the Pet Store demo app that includes 'summon' and
'summon-conjur' in the demo Docker image. The new Pet Store image is causing a
problem when the E2E workflow attempts to build its own Docker image
by also adding 'summon' and 'summon-conjur' to this image, causing a
conflict.
This change also includes a temporary fix for failures in the Helm test
validation CI. This is failing because there are Helm test hooks applied
to the test ConfigMaps. For some reason, Helm doesn't create the Helm
test ConfigMaps for 'helm test ...' when these hooks are present, so
these hooks are being backed out for now.
**If you are preparing for a release**, have you run the following manual tests to verify existing functionality …
> Downgrade pet store app to fix broken E2E workflow tests

- CHANGELOG.md
- Dockerfile
- Dockerfile.helm-unit-test
Upgrades the base Alpine image used for Helm test functionality for various Helm charts from `alpine:3.12` to `alpine:3.14` in order to resolve CVE-2021-36159.
Also included is a change of other Alpine base images from `alpine:latest` to `alpine:3.14` (the current `latest`), effectively pinning these images to the current latest, so that Alpine images used are consistent and not a moving target.
Resolves #374
> Upgrade Alpine to v3.14 to resolve CVE-2021-36159

- bin/test-workflow/2_admin_load_conjur_policies.sh
- bin/test-workflow/6_app_deploy_backend.sh
- bin/test-workflow/7_app_deploy.sh
- bin/test-workflow/openshift/conjur-cli.yml
- bin/test-workflow/utils.sh
- helm/conjur-app-deploy/charts/app-secretless-broker/templates/test_app_secretless_broker.yaml
- helm/conjur-app-deploy/charts/app-secretless-broker/values.yaml
- helm/conjur-app-deploy/charts/app-summon-sidecar/templates/test-app-summon-sidecar.yaml
- helm/conjur-app-deploy/charts/app-summon-sidecar/values.yaml
This updates the test-workflow scripts for use on Openshift.
Also required for this is a change in [conjur-oss-helm-chart](https://github.com/cyberark/conjur-oss-helm-chart/pull/163)
Resolves #346 
> Updates the app deployment for Openshift

- bin/test-helm-unit
- helm/conjur-app-deploy/charts/app-secretless-broker/README.md
- helm/conjur-app-deploy/charts/app-secretless-broker/test-schema
- helm/conjur-app-deploy/charts/app-secretless-broker/test-unit
- helm/conjur-app-deploy/charts/app-secretless-broker/tests/conjur_authn_configmap_test.yaml
- helm/conjur-app-deploy/charts/app-secretless-broker/tests/test_app_secretless_broker_test.yaml
- helm/conjur-app-deploy/charts/app-secretless-broker/values.schema.json
- helm/conjur-app-deploy/charts/app-secretless-broker/values.yaml
Adds Helm unittest and schema validation tests to the recently added test app + Secretless Broker subchart.
Resolves #376
> Add unittest and schema validation tests to Secretless app subchart

- bin/test-helm-unit
- helm/conjur-app-deploy/Chart.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/test-schema
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/Chart.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/README.md
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/templates/NOTES.txt
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/templates/secret.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/templates/test_app_secrets_provider_standalone.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/test-schema
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/test-unit
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/tests/test_app_secrets_provider_standalone_test.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/values.schema.json
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/values.yaml
This change adds a Helm subchart to the `conjur-app-deploy` main Helm chart that can be used to deploy:
- A sample "Pet Store" application that uses a Kubernetes Secret to configure its backend database credentials
- A "standalone" Secrets Provider Job that, upon startup, updates the Kubernetes Secret that is used by the "Pet Store" application with backend database credentials that the Secrets Provider has retrieved from Conjur.
The deployment of the "standalone" Secrets Provider is done by using the Secrets Provider Helm chart as a [Helm chart dependency](https://helm.sh/docs/helm/helm_dependency/) of the `app-secrets-provider-standalone` subchart.
This change also includes Helm unittest test cases and Helm schema validation tests for the new subchart.
NOTE: Adding this Helm subchart to …
> Add Helm subchart for test app w/ Secrets Provider in standalone mode

- .gitignore
- bin/test-workflow/7_app_deploy.sh
- bin/test-workflow/8_app_verify_authentication.sh
- bin/test-workflow/policy/app-access.yml
- bin/test-workflow/policy/load_policies.sh
- bin/test-workflow/policy/templates/project-authn-def.template.yml
- bin/test-workflow/start
This change adds the deployment of an application that uses the Secrets
Provider in standalone mode to the E2E application deployment scripts.
Resolves #292
> Adds app that uses Secrets Provider in standalone mode to E2E scripts

- helm/conjur-config-namespace-prep/templates/authenticator_rolebinding.yaml
- helm/conjur-config-namespace-prep/templates/conjur_connect_configmap.yaml
- helm/conjur-config-namespace-prep/tests/authenticator_rolebinding_test.yaml
- helm/conjur-config-namespace-prep/tests/conjur_connect_configmap_test.yaml
Allows for custom names of ConfigMap and RoleBinding entities created by the Namespace prep Helm chart.
Includes Helm unit tests to confirm this behavior.
Resolves #383
> Allow custom names for Namespace prep entities

- bin/test-workflow/0_prep_env.sh
- bin/test-workflow/7_app_deploy.sh
- bin/test-workflow/8_app_verify_authentication.sh
- bin/test-workflow/start
- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/test_app_secrets_provider_init.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/values.yaml
- helm/conjur-config-namespace-prep/generated/conjur-config-namespace-prep.yaml
In #272, the app deploy Helm Chart was updated to support deployment of the app + Secrets Provider init container.
Here, the E2E workflow scripts are updated to deploy and test against this application.
Also, updates the app + Secrets Provider init container subchart for Openshift deployment, similar to changes to the `app-summon-sidecar` and `app-secretless-broker` subcharts made in PR #346.
> Include Secrets Provider init app in E2E workflow

- helm/conjur-app-deploy/charts/app-secretless-broker/templates/test_app_secretless_broker.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/test_app_secrets_provider_init.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/templates/test_app_secrets_provider_standalone.yaml
- helm/conjur-app-deploy/charts/app-summon-sidecar/templates/test-app-summon-sidecar.yaml
This change modifies the deployment manifests for applications in the E2E workflow so that the test application runs as a non-root user. Running containers using non-root user/group is considered best practice for Kubernetes workloads.
This is accomplished by setting the associated 'PodSecurityContext' for each deployment so that every container (i.e. the application container as well as the authentication container, if present) are run using:
- The 'nobody' non-root user (UserID 66634)
- The 'nobody' non-root group (GroupID 65534)
- fsGroup of 65534 (i.e. directories and files for all shared volumes
are created using a Group ID of 65534).
In some cases, this also requires creating `volumeMounts` for containers and `emptyDir` Volumes for the Pods for directories to which the authenticator …
> Runs test apps in E2E workflow as non-root user

- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/values.yaml
Currently, the E2E workflow for an application that uses the Secrets Provider in standalone ("app") mode uses the default Job name for the Secrets Provider as defined by the Secrets Provider Helm chart. The Secrets Provider Helm chart uses the charts Release name as a default:
https://github.com/cyberark/secrets-provider-for-k8s/blob/main/helm/secrets-provider/values.yaml#L19-L20
Normally, using the Helm chart release name makes sense when the Secrets Provider Helm chart is installed directly. However, for `conjur-authn-k8s-client` E2E workflow test app deployment, this Helm chart is installed as a dependency (i.e. downloaded subchart), so that the Helm release name is the Release name for the parent chart, which in
this case is typicall "test-app". Using this "test-app" as the name of …
> Use 'secrets-provider' as Job name for standalone Secrets Provider

- bin/test-workflow/2_admin_load_conjur_policies.sh
- bin/test-workflow/utils.sh
There are a couple of functions in 'utils.sh' file for the E2E workflow test scripts that use the Bash 'eval' command:
- run_conjur_cmd_as_admin()
- wait_for_it()
The calls made to these two functions pass in a command string, and these functions in turn execute the command strings using 'eval'.
In some cases, the callers to these functions include environment variable values in the command strings that they dynamically generate. Here is one example of a call to 'wait_for_it':
```
wait_for_it 300 "$cli exec $conjur_cli_pod -- \
bash -c \"
conjur_appliance_url=${CONJUR_APPLIANCE_URL} \
CONJUR_ACCOUNT=${CONJUR_ACCOUNT} \
CONJUR_ADMIN_PASSWORD=${CONJUR_ADMIN_PASSWORD} \
DB_PASSWORD=${SAMPLE_APP_BACKEND_DB_PASSWORD} \
TEST_APP_NAMESPACE_NAME=${TEST_APP_NAMESPACE_NAME} \ …
```
> Fix calls to functions that use 'eval' in E2E test scripts

- helm/conjur-app-deploy/README.md
The sample application Helm Chart README describes:
- the types of applications that it can deploy
- using the Helm chart to install sample applications
- configurable values, both universal and those unique to each subchart
Resolves #264 
> Add sample app Helm Chart README

- Jenkinsfile
- bin/test-workflow/0_prep_env.sh
- bin/test-workflow/2_admin_load_conjur_policies.sh
- bin/test-workflow/6_app_deploy_backend.sh
- bin/test-workflow/8_app_verify_authentication.sh
- bin/test-workflow/Dockerfile
- bin/test-workflow/cleanup_helm.sh
- bin/test-workflow/cleanup_namespaces.sh
- bin/test-workflow/dev-start.sh
- bin/test-workflow/platform_login.sh
- bin/test-workflow/secrets.yml
- bin/test-workflow/start
- bin/test-workflow/stop
- bin/test-workflow/utils.sh
- helm/conjur-app-deploy/charts/app-secretless-broker/templates/test_app_secretless_broker.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/test_app_secrets_provider_init.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-standalone/templates/test_app_secrets_provider_standalone.yaml
- helm/conjur-app-deploy/charts/app-summon-sidecar/templates/test-app-summon-sidecar.yaml
Updating the start script and cleanup Openshift.
Updating the start scripts running Openshift E2E tests on Jenkins.
Also updating the cleanup scripts to handle the unique conjur-oss
namespace and to check if resources exist before deleting to avoid
errors when it can't find the resources.
Also added a new dev-start script for developers to help with bringing up Openshift.
This also fixes an intermittent issue with GKE test failing with the error
'''
./2_admin_load_conjur_policies.sh: line 87: ./generated/app-test-f059b781-e.cluster-authn-svc.yml: Permission denied
'''
by changing the permissions of the generated directory.
Resolves #N/A
> Updating scripts for Jenkins on Openshift

- Jenkinsfile
- bin/test-workflow/0_prep_env.sh
- bin/test-workflow/1_deploy_conjur.sh
- bin/test-workflow/2_admin_load_conjur_policies.sh
- bin/test-workflow/dev-start.sh
- bin/test-workflow/platform_login.sh
- bin/test-workflow/start
- bin/test-workflow/stop
- bin/test-workflow/utils.sh
- Minor changes to get a new E2E flow working (authenticator sidecars in OpenShift and Conjur Enterprise and follower in Jenkins)
- Minor cleanups and deflaking
Resolves #245
> Implement E2E workflow for authenticator sidecars in OpenShift and Conjur Enterprise and follower in Jenkins

- bin/test-workflow/6_app_deploy_backend.sh
When running KinD in a VM, there was an error with Insufficient cpu.
```
Events:
Type     Reason            Age                From               Message
----     ------            ----               ----               -------
Warning  FailedScheduling  4s (x4 over 112s)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu.
```
Adding an exit inside
```
if [[ "$ret_val" != 0 ]]; then
```
The purpose of this check is to display debug information if the Helm chart fails, but we
should exit after so it is clear what fails.
Resolves #N/A
> Add exit on failure.

- helm/conjur-app-deploy/charts/app-secrets-provider-init/templates/test_app_secrets_provider_init.yaml
This change adds a Volume and VolumeMount for the Secrets Provider init container application Helm chart so that Pod Annotations can be exposed to the Secrets Provider via the Kubernetes Downward API.
This will help with testing the M1 Push-to-File feature for the Secrets Provider.
> Adds volume to expose Annotations for Secrets Provider init app

- pkg/authenticator/authenticator.go
- pkg/authenticator/authenticator_test.go
- pkg/authenticator/authenticator_test_server.go
- Refactor unit test on the Authenticator class to test all scenarios through the public interface (i.e. the `Authenticate()` method) as opposed to directly testing internal implementation methods (e.g. `generateCSR()`)
- Privatise methods that are not used externally (ie. in main.go)
[ONYX-13586](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-13586)
> ONYX-13586-refactor-authenticate-tests

- bin/test-workflow/README.md
Update the quick start guide in the README here (https://github.com/cyberark/conjur-authn-k8s-client/tree/master/bin/test-workflow) to describe which personas are running which set of scripts according to the personas outlined here (https://github.com/cyberark/dap-wiki/tree/master/how-to-guides/kubernetes).
Personas:
- k8s cluster admin
- Conjur admin
- App developer / devops engineer
- Added personas to README sections describing scripts.
- Fixed links to policy files that were broken by #409
Resolves #323
CyberArk internal issue link: [ONYX-12652](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-12652)
changes, or
> Describe personas for E2E Workflow Scripts

- .github/workflows/e2e-workflow.yaml
- Jenkinsfile
- bin/test-workflow/7_app_deploy.sh
- bin/test-workflow/8_app_verify_authentication.sh
- bin/test-workflow/policy/app-policy.yml
- bin/test-workflow/policy/load_policies.sh
- bin/test-workflow/policy/templates/app-grants.template.yml
- bin/test-workflow/policy/templates/app-identities-policy.template.yml
- bin/test-workflow/start
- helm/conjur-app-deploy/Chart.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/Chart.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/README.md
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/templates/NOTES.txt
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/templates/rbac.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/templates/test_app_secrets_provider_p2f.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/test-schema
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/test-unit
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/tests/test_app_secrets_provider_p2f_test.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/values.schema.json
- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/values.yaml
- helm/conjur-app-deploy/values.yaml
This PR includes a Helm subchart to test Secrets Provider in Push-to-File mode in the E2E environment.
- Added a Helm subchart for a demo app with Secret Provider in Push-to-File mode
- P2F writes a custom spring config file to the shared volume
- The custom config file is set at runtime using the `--spring.config.location` flag when starting the demo app
- Adds schema and unit tests for the SP P2F subchart
merged.*
changes, or
> Include Push-to-File Secrets Provider in E2E test workflow

- Dockerfile.junit
- Dockerfile.test
- go.mod
Use the latest major version of Go
Note: `Dockerfile` uses the `goboring/golang` image for FIPS compliance (see https://github.com/cyberark/conjur-authn-k8s-client/blob/master/design/fips-compliance.md) which does not yet have a 1.17 release. This has been left to use 1.16 for the time being.
CyberArk internal issue link: [ONYX-14556](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14556)
changes, or
> Update golang to 1.17

- helm/conjur-app-deploy/charts/app-secrets-provider-p2f/templates/test_app_secrets_provider_p2f.yaml
When the E2E test scripts are run, including the deployment of an application that uses the Secrets Provider as an Init container in Push-to-File mode, and then that Deployment is modified to use a "freshly-built" Secrets Provider image (i.e. image built using most recent code from Secrets Provider branch), then the Pet Store application should successfully come up.
Currently, when a "freshly-built" Secrets Provider image is used, the Pet Store application fails because the secret file that is created is defaulting to YAML format (because the `secret-file-format.<secret-group>` annotation is not explicitly set to `template`). In this scenario, the secret file needs to be a Spring boot application format file, built using the custom template supplied via Annotation.
Added an Annotation to …
> Adds file format annotation for Secrets Provider P2F helm chart

- bin/test-workflow/0_prep_env.sh
- bin/test-workflow/7_app_deploy.sh
- bin/test-workflow/utils.sh
The `bin/test-workflow/start` script can successfully deploy the Secrets Provider Push-to-File deployment.
This is currently broken because of a recent change that I made to use a file format of `template` for the push-to-file deployment. The tests use the `latest` version of Secrets Provider by default, and the `latest` version does not tolerate a file format setting of `template`.
This change modifies the default version of Secrets Provider that is used in the E2E test workflow scripts from 'latest' to 'edge'. This is done by adding environment variables for the E2E tests scripts that can be used to set the versions to use for Secrets Provider and for Secretless broker. These settings now default to `edge` and `latest`, respectively.
changes, or
> Use edge version of Secrets Provider in E2E test scripts

- CHANGELOG.md
- bin/test-workflow/0_prep_env.sh
- helm/conjur-config-cluster-prep/test-schema
- helm/conjur-config-cluster-prep/values.schema.json
The conjur-config-cluster-prep Helm schema tests check that the certificate file path
has `files` or `tests` in the path. The file path is not restricted
to those directories and it should allow other paths.
The user should be able to specify an alternative path for the certificate file.
The files directory is only the default for the `get-conjur-cert.sh`
script but it is not required to be in this directory and the script is not required to be used,
this is only a helper script, the user can use an alternate method to get the cert.
Note that the certificate must be located inside the chart as Helm does not have access to
files outside the chart.
Removed the check for `files` in the schema verification.
Also added a change to bin/test-workflow/0_prep_env.sh
to use an existing …
> Remove pattern check in schema validation for cert file path

- .gitignore
- Dockerfile
- bin/build
- bin/build_utils
Background:
On CyberArk dev laptops, golang module dependencies are
downloaded with a corporate proxy in the middle. For these connections to
succeed we need to configure the proxy CA certificate in build containers.)
Docker-based build of the conjur-authn-k8s images (using `./bin/build`) works on
a CyberArk NG laptop.
Currently, this build fails when Go modules (new dependencies) are being loaded
on CyberArk dev laptops, since this is done with a corporate proxy at the
corporate network edge. The Docker containers used for this build do not
natively have the CyberArk CA certificate loaded in their trusted certificate store,
so the connection fails with an unknown certificate error.
When builds are run on CyberArk NG laptops, the corporate CA cert is downloaded
using the `security …
> Fix Docker-based builds to work on CyberArk NG laptops

- CHANGELOG.md
- pkg/authenticator/version.go
> Bump to version 0.23.0

- CONTRIBUTING.md
- bin/test-workflow/7_app_deploy.sh
- bin/test-workflow/8_app_verify_authentication.sh
- bin/test-workflow/policy/app-policy.yml
- bin/test-workflow/policy/load_policies.sh
- bin/test-workflow/policy/templates/app-grants.template.yml
- bin/test-workflow/policy/templates/app-identities-policy-jwt.template.yml
- bin/test-workflow/start
- helm/conjur-app-deploy/Chart.yaml
- helm/conjur-app-deploy/charts/app-secretless-broker-jwt/Chart.yaml
- helm/conjur-app-deploy/charts/app-secretless-broker-jwt/README.md
- helm/conjur-app-deploy/charts/app-secretless-broker-jwt/files/secretless_config.yaml
- helm/conjur-app-deploy/charts/app-secretless-broker-jwt/templates/NOTES.txt
- helm/conjur-app-deploy/charts/app-secretless-broker-jwt/templates/secretless_config_configmap.yaml
- helm/conjur-app-deploy/charts/app-secretless-broker-jwt/templates/test_app_secretless_broker.yaml
- helm/conjur-app-deploy/charts/app-secretless-broker-jwt/values.schema.json
- helm/conjur-app-deploy/charts/app-secretless-broker-jwt/values.yaml
- helm/conjur-app-deploy/values.yaml
Added automation for secretless broker as side car running on local kind cluster with conjur oss in the cluster
Currently not part of CI but can be in the future when conjur-oss with public keys released
ONYX-15241
merged.*
changes, or
> ONYX-15241: Add automation for secretless-broker with JWT flow

- bin/test-workflow/1_deploy_conjur.sh
- bin/test-workflow/2_admin_load_conjur_policies.sh
- bin/test-workflow/3_admin_init_conjur_cert_authority.sh
- bin/test-workflow/4_admin_cluster_prep.sh
- bin/test-workflow/5_app_namespace_prep.sh
- bin/test-workflow/6_app_deploy_backend.sh
- bin/test-workflow/7_app_deploy.sh
- bin/test-workflow/8_app_verify_authentication.sh
- bin/test-workflow/utils.sh
When the E2E test scripts fail:
- Kubernetes resources are dumped from either the Conjur namespace or the application namespace (depending upon at which point the tests fail)
- The test failure is announced in a banner as soon as a fatal error is detected (before any dumping of Kubernetes resources and before everything is cleaned up) so that it's clearer exactly where the error occurs.
Also, run Helm install commands without the `--debug` flag to make test output much less verbose for successful test runs.
- Bash trap functions are added to test scripts to trap on EXIT. In the trap functions, if exit status is non-zero,  an announcement (i.e. banner msg) that the test has failed is displayed, and a dump of Kubernetes resources is performed before test cleanup begins.
- The `--debug` flag …
> Adds dump of K8s resources and announces failure on E2E test fail

- Jenkinsfile
- bin/test-workflow/start
Builds on Conjur OSS in OpenShift v(next) don't fail with the following error:
`helm.go:81: [debug] serviceaccounts "test-app-summon-sidecar" already exists`
The E2E workflow test scripts in this repo are designed to run either `authn-k8s` applications exclusively, or `jwt` authentication applications exclusively (depending upon whether the `--jwt` flag is selected or not). If an `authn-k8s` application is being deployed (e.g. `summon-sidecar`), and its equivalent `jwt` authentication based application is also deployed (e.g. `summon-sidecar-jwt`), then there will be K8s resource name conflicts for resources in the `app-test` Namespace.
The Jenkins CI runs for OpenShift "next" platform version was not using the `--ci-apps` flag, and was not explicitly selecting applications to be deployed …
> Run only authn-k8s applications for OpenShift(next) Jenkins CI

- pkg/authenticator/k8s/authenticator.go
Log the requests IP address when there is a login error
Add a function to find and print he ip address taken from the host name.
- _Are there relevant screenshots you can add to the PR description?_
CyberArk internal issue link: [ONYX-14476](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-14476)
Improved error message in authenticator client when request goes to an unhealthy master (502 error code doesn't reveal what IP address the name resolved to). Log the node's IP address when the connection fails.
changes, or
> Log the master IPS when there is a login in error

- .github/CODEOWNERS
The Palm Tree team are no longer code-owners of this project
and thus should be removed from the CODEOWNERS file
> Remove Palm Tree team from project ownership

- helm/conjur-config-cluster-prep/templates/golden_configmap.yaml
- helm/conjur-config-cluster-prep/tests/golden_configmap_test.yaml
- helm/conjur-config-namespace-prep/templates/conjur_connect_configmap.yaml
- helm/conjur-config-namespace-prep/tests/conjur_connect_configmap_test.yaml
For both cluster prep and Namespace prep Helm charts, any trailing '/' characters are trimmed from the appliance URL set by the user or read from the Golden ConfigMap, respectively.
For both cluster prep and Namespace prep Helm charts, the `trimSuffix` Sprig function is used to trim any trailing '/' characters from appliance URLs that are supplied by the user or read from the Golden ConfigMap, respectively.
**NOTE:** Trimming the '/' characters in the Namespace prep Helm chart isn't absolutely necessary, but it's added just as a defensive SW measure.
N/A
changes, or
> Trims trailing slash chars from appliance URL in config Helm charts

- bin/test-workflow/6_app_deploy_backend.sh
Fix version of bitanmi postgresql version so pipelines will pass and won't be broker by any changes of bitnami.
If there is a better solution that will also work in openshift i will close this PR.
> Fix version of bitnami/postgresql helm

- helm/conjur-app-deploy/charts/app-secrets-provider-p2f-jwt/templates/test_app_secrets_provider_p2f.yaml
In automation of secrets provider with JWT in Push 2 file mod. Move JWT_TOKEN_PATH to annotation 
conjur.org/jwt-token-path
> ONYX-16318: Move JWT token path to annotation in p2f

- helm/conjur-config-namespace-prep/generated/conjur-config-namespace-prep.yaml
- helm/conjur-config-namespace-prep/templates/conjur_connect_configmap.yaml
- helm/conjur-config-namespace-prep/tests/conjur_connect_configmap_test.yaml
The Namespace Prep Helm chart fails and emits a clear error message whenever expected fields are missing in the Golden ConfigMap.
Added calls to `required` when fields are read from the Golden ConfigMap.
N/A
changes, or
> Added checks for missing fields in Golden ConfigMap

- bin/test-workflow/start
- helm/conjur-config-cluster-prep/templates/golden_configmap.yaml
In recent CI runs, the stage running end-to-end tests against Conjur Enterprise in GKE succeed without installing the Namespace Prep Helm chart or deploying the test apps.
From a [passing Jenkins run](https://jenkins.conjur.net/blue/organizations/jenkins/cyberark--conjur-authn-k8s-client/detail/test-openshift-next/1/pipeline/163#step-172-log-1706):
```
++++++++++++++++++++++++++++++++++++++
Installing cluster prep chart
++++++++++++++++++++++++++++++++++++++
. . .
The Conjur/Authenticator Namespace preparation is complete.
The following have been deployed:
- Golden ConfigMap
- Authenticator ClusterRole
++++++++++++++++++++++++++++++++++++++
Removing test environment
++++++++++++++++++++++++++++++++++++++
```
Updating this led to another bug:
[Jenkins …
> Bugfixes: Enterprise-in-GKE test not deploying test apps

- CHANGELOG.md
- helm/conjur-app-deploy/Chart.yaml
- helm/conjur-config-cluster-prep/Chart.yaml
- helm/conjur-config-cluster-prep/generated/conjur-config-cluster-prep.yaml
- helm/conjur-config-namespace-prep/Chart.yaml
- pkg/authenticator/version.go
Release the Authenticator client.
- Update `CHANGELOG.md` to include missing entries
- Update `version.go` from 0.23.0 to 0.23.1
- Update Configuration Helm Chart versions from 0.1.2 to 0.1.3
- Re-generate raw manifests
- No dependency updates, no need to update `NOTICES.txt`
merged.*
changes, or
> Bump client version to 0.23.1 and Config Helm chart versions to 0.1.3

- bin/test-workflow/7_app_deploy.sh
- bin/test-workflow/8_app_verify_authentication.sh
- bin/test-workflow/policy/app-policy.yml
- bin/test-workflow/policy/load_policies.sh
- bin/test-workflow/policy/templates/app-grants.template.yml
- bin/test-workflow/policy/templates/app-identities-policy.template.yml
- bin/test-workflow/start
- helm/conjur-app-deploy/Chart.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/Chart.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/README.md
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/templates/NOTES.txt
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/templates/rbac.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/templates/test_app_secrets_provider_rotation.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/test-schema
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/test-unit
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/tests/test_app_secrets_provider_rotation_test.yaml
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/values.schema.json
- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/values.yaml
- helm/conjur-app-deploy/values.yaml
Implement end-to-end smoke tests for secrets rotation in secrets provider.
- Added helm charts and bash tests for secrets rotation in secrets provider.
- **New test must be run manually with `./bin/test-workflow/start -a secrets-provider-rotation`. They're currently not run in the CI.**
CyberArk internal issue link: [ONYX-16912](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-16912)
changes, or
> Add E2E tests for secrets rotation

- helm/conjur-app-deploy/charts/app-secrets-provider-rotation/templates/test_app_secrets_provider_rotation.yaml
For the application Helm chart for the Secrets Provider running in Push-to-File mode with secret rotation support, it is desirable that we include:
- A Kubernetes postStart lifecycle hook that delays startup of the application until the SP has finished creating the secret file(s).
- A liveness probe for the application container that forces the application container to be restarted whenever the date of the secrets files change.
The following changes are made to the `app-secrets-provider-rotation` Helm chart in order to delay the application container from starting until after the Secrets Provider sidecar container has finished creating the secret file(s) in the secrets shared volume:
- A 'postStart' lifecycle hook is added to the SP container definition.
- The SP container definition is …
> Adds poststart hook to delay app startup until SP P2F completes

- helm/conjur-config-cluster-prep/README.md
- helm/conjur-config-cluster-prep/templates/golden_configmap.yaml
- helm/conjur-config-cluster-prep/tests/golden_configmap_test.yaml
When a user does a Helm install of the cluster prep Helm chart, and uses a `conjur.certificateFilePath` value that points to a file that is either outside of the Helm chart directory/subdirectory, or is non-existent, then an error should be displayed clearly indicating what the error is, rather than creating a Golden ConfigMap with empty fields for Conjur certificate.
Added a check into the Golden ConfigMap template in the Helm chart that Helm was actually able to find the file pointed to by `conjur.certificateFilePath`.
N/A
merged.*
changes, or
> Adds check for cert filepath being in cluster prep chart dirs/subdirs

- Jenkinsfile
Add a Jenkins step to validate log message files such as [this](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/pkg/log/messages/error_messages.go) and alert to any mismatches between the IDs of the `const` variables and the IDs in the actual message string.
It is common to copy and paste lines from these files and simply change the message and increment the number in the variable name, but forget to change the ID in the message string. This script would detect this automatically.
An example of where this mistake happened can be found [here](https://github.com/cyberark/secrets-provider-for-k8s/pull/449#discussion_r837549729)
- Added a Jenkins step that finds files matching "*messages.go" and parses them for log messages. It then verifies that all log messages are consistent …
> Validate log messages

- .github/workflows/e2e-workflow.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- Dockerfile
- Dockerfile.helm-unit-test
- Dockerfile.test
- Jenkinsfile
- bin/build
- bin/build_utils
- bin/publish
- bin/test-workflow/0_prep_env.sh
- bin/test-workflow/1_deploy_conjur.sh
- bin/test-workflow/start
- bin/validate-helm
- dev/Dockerfile.debug
- go.mod
- Project pipeline moved to azure-linux executor allowing public IP
access for workflow tests.
- Reconfigured bin/publish to perform releases and promotions
of contianer images based on optional flag parameters.
- Added additional functions in bin/build_utils for the automated releases.
- Maintained legacy bin/build_utils functions that are currently no longer in
use, but might provide useful in the future.
- Added submodule for conjur-opentelemetry-tracer upstream dependency.
- Moved temp directory creation to /bin/test-workflow/start. The temp directory
must be created by the jenkins user to prevent permission issues within
the directory. This also removes the possibility of a race condition when parallel
test stages are running and allows for developers to skip tests
during the …
> Added automated release process to project pipeline.

- Dockerfile.junit
- Dockerfile.test
- Jenkinsfile
- bin/test
Report Go unit test coverage of `pkg/` and `cmd/` files to Cobertura and CodeClimate.
- Add Go test coverage tools to `Dockerfile.junit`
- Update `bin/test` to convert Go coverage report to format consumable by Cobertura
- Add CodeClimate reporting to `Jenkinsfile` 
- Use `go test` flag `-coverpkg`, which allows tests to record coverage for source files in other packages.
- Some packages use a `tests` sub-package for test files, which leaves the parent package with 0% coverage.
- Some packages, like `common` and `config`,  should register coverage from tests in packages that use their common functionality.
See: [Resulting Cobertura coverage report in Jenkins](https://jenkins.conjur.net/job/cyberark--conjur-authn-k8s-client/job/enable-coverage-report/9/cobertura/)
CyberArk internal issue …
> Enable test coverage reporting with Cobertura and CodeClimate

- Jenkinsfile
- bin/publish
Intermediate versions of `cyberark/conjur-authn-k8s-cluster-test` need to be published for edge releases, then promoted to latest and proper versions on promotion.  The publish was missing from the edge release section.
> Add handling for test image publishing

- CHANGELOG.md
- Dockerfile
Built images should not have critical or high security vulnerabilities.
Updated the Red Hat UBI base image.
merged.*
changes, or
> Update the Red Hat image for cve-2022-1271

- CHANGELOG.md
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Prep CHANGELOG.md for next release as will promote current release build once it completes. 
- Added 0.23.6 section to CHANGELOG.md
- Added new version links at end of CHANGELOG.md
> Prep CHANGELOG for next release

- CHANGELOG.md
- go.mod
- go.sum
Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Remove versions of gopkg.in/yaml.v3 prior to v3.0.1 from the dependency tree.
Replace the remaining old version and force it to 3.0.1
CyberArk internal issue: CONJSE-1378
merged.*
changes, or
> Use replace to remove yaml.v3 prior to 3.0.1 from consideration

- go.mod
Projects that include conjur-authn-k8s-client as a library will break with a version set to `latest` in `go.mod`.  This is an issue in the parser used even though it will be validly substituted.  Automated releases rely on pulling the latest version of internally managed projects.  This change will allow `go mod tidy` to properly parse the `go.mod` from this project and use the latest version of conjur-opentelemetry-tracer.
- Use `replace` in go.mod to pull in the latest version without breaking parsing
Downstream projects successfully build using conjur-authn-k8s-client as a library
changes, or
> Update to allow parsing of go.mod in downstream projects

- CONTRIBUTING.md
- bin/publish
The conjur-authn-k8s-client image does not appear to be getting pushed to RedHat's platform successfully so we can not complete the [last few release](https://github.com/cyberark/conjur-authn-k8s-client/blob/master/CONTRIBUTING.md#publish-the-red-hat-image%20steps) that involve logging into RedHat's platform and publishing the image.
Investigate the CI pipeline and see if there are any sources of error when pushing to RedHat.
- Added a script to the release-tools repository in https://github.com/conjurinc/release-tools/pull/38 which scans the OpenShift images using Red Hat's newly mandatory [preflight](https://github.com/redhat-openshift-ecosystem/openshift-preflight) tool.
CyberArk internal issue link: [ONYX-21631](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-21631)
CHANGELOG …
> Scan OpenShift image after pushing to Red Hat

- Jenkinsfile
- bin/test-workflow/0_prep_env.sh
- bin/test-workflow/1_deploy_conjur.sh
The desired outcome of this PR is twofold:
1) To validate the `authn-k8s-client` against the latest Conjur release
2) To make it easier to run tests with different Conjur enterprise images
This PR makes the Conjur enterprise appliance tag a test suite input configured with an environment variable `CONJUR_APPLIANCE_TAG`. This tag is configured in Jenkins to use the latest internal release of the Conjur Enterprise image.
CyberArk internal issue link: [ONYX-25164](https://ca-il-jira.il.cyber-ark.com:8443/browse/ONYX-25164)
merged.*
changes, or
- x ] This PR does not require updating any documentation
> Make appliance tag a configurable test input

- CHANGELOG.md
- bin/test-workflow/0_prep_env.sh
- bin/test-workflow/2_admin_load_conjur_policies.sh
- bin/test-workflow/4_admin_cluster_prep.sh
- bin/test-workflow/5_app_namespace_prep.sh
- bin/test-workflow/policy/templates/app-identities-policy.template.yml
- bin/test-workflow/utils.sh
- helm/conjur-config-cluster-prep/generated/conjur-config-cluster-prep.yaml
- helm/conjur-config-cluster-prep/templates/clusterrole.yaml
Update our end-to-end test workflow to validate Authn-K8s namespace label selector restriction.
- Update Cluster Prep Helm chart ClusterRole to provide `get` permission on namespaces.
- The `test-app-summon-sidecar` host is configured with the `namespace-label-selector` resource restriction. If the `summon-sidecar` app succeeds, then namespace label-based Authn-K8s is functional.
N/A
merged.*
changes, or
> Update summon-sidecar E2E test to use namespace-label authn-k8s

- bin/test-workflow/8_app_verify_authentication.sh
- bin/test-workflow/utils.sh
- helm/conjur-config-cluster-prep/generated/conjur-config-cluster-prep.yaml
- helm/conjur-config-cluster-prep/templates/serviceaccountsecret.yaml
Ability to determine why containers are failing during CI.
Log Kubernetes container outputs to the Jenkins CI console log on failure.
CyberArk internal issue link: ONYX-26951
merged.*
changes, or
> Dump K8S pod logs on failure

- bin/test-workflow/4_admin_cluster_prep.sh
- bin/test-workflow/6_app_deploy_backend.sh
- bin/test-workflow/cleanup_helm.sh
- bin/test-workflow/stop
Update the E2E tests for sidecar injector
- Update the `sed` line in `4_admin_cluster_prep.sh` to be compatible with mac
- Removed adding serviceaccountsecret.yaml as this is now in the sidecar injector repo
- Added cleanup of the sidecar injector Helm chart.
- removed extra debug lones 
merged.*
changes, or
> update e2e tests for sidecar injector

- bin/publish
Push images to quay.io (instead of scan.connect.redhat.com) for preflight scanning
merged.*
changes, or
> Fix Redhat registry pushing

- Dockerfile
This addresses a build error that seems to have been introduced with the latest busybox release
Remove busybox from Dockerfile as latest version causes build errors
CyberArk internal issue ID: [ONYX-24057]
merged.*
changes, or
> Remove busybox from Dockerfile 

- Jenkinsfile
- bin/coverage
- bin/test
Several of our CI pipelines follow [this pattern](https://github.com/cyberark/secrets-provider-for-k8s/blob/main/bin/test_unit#L31) where the script that runs unit tests sets +e to prevent unit test failure from stopping the script from running. I believe this was done to ensure that the junit tests would run even if the tests failed, but it's having the unfortunate side effect of showing the unit testing phase as green in Jenkins when a unit test fails, making it a bit unclear what's going on.
Break the junit logic into a separate script that can be run independently from the unit tests in a "post-always" block in the Jenkinsfile and return the error code when unit test(s) fail.
merged.*
changes, …
> Fix false positive tests in test stage

- CHANGELOG.md
- bin/test-workflow/1_deploy_conjur.sh
Seeing the following error with the latest CI runs.
```[2023-01-27T15:00:50.184Z] Running Command (on conjur-master-1.mycompany.local): docker exec cyberark-dap evoke seed follower conjur-follower.mycompany.local > /opt/cyberark/dap/seeds/follower-seed.tar
[2023-01-27T15:00:55.464Z] psql: could not connect to server: No such file or directory
[2023-01-27T15:00:55.464Z]     Is the server running locally and accepting
[2023-01-27T15:00:55.464Z]     connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
Added a wait for the master before provisioning the follower
merged.*
changes, or
> Adding a wait for the master before deploying the follower

- Dockerfile
- Dockerfile.helm-unit-test
- bin/test-workflow/Dockerfile
Address failing builds due to high severity CVE-2022-28948 loading in from yq
* Use latest release of yq (or build from source)
* Add /src folder as git safe directory (from https://github.com/cyberark/conjur-authn-k8s-client/pull/500)
NOTE: using latest fixes the intended CVE but there is still a high severity CVE found: CVE-2022-41721. It should be fixed with this [PR](https://github.com/mikefarah/yq/pull/1540) in the next yq release which I assume will appear in the next week or so. In the meantime we could add a .trivyignore entry to get passing builds. (cc @andytinkham)
Alternatively I've updated the dockerfile to build yq from source which has the CVE fix already (requires using golang:alpine image for helm test image)
*At least 1 todo must be completed in the sections below for the …
> Use latest yq release (CVE-2022-28948)

- CHANGELOG.md
- Dockerfile
- Dockerfile.helm-unit-test
- Dockerfile.junit
- Dockerfile.test
- go.mod
- go.sum
This pull request address both upgrading the 'golang.org/x/sys' dependency to resolve CVE-2022-29526 and updating the Dockerfiles to 1.19 to uphold the 'boringcrypto' fix as well as keeping everything up-to-date.
- updated CHANGELOG
- upgraded image in Dockerfile to 1.19
- upgraded image in Dockerfile.helm-unit-test to 1.19
- upgraded image in Dockerfile.junit to 1.19 & corresponding syntax fix
- upgraded image in Dockerfile.test to 1.19
- upgraded go.mod and go.sum
changes, or
- [] No behavior was changed with this PR
> Upgrade base image in Dockerfiles to 1.19

- Jenkinsfile
Turn on Cobertura autoUpdateHealth and  autoUpdateStability
Recently Cobertura autoUpdateHealth and  autoUpdateStability was turned off to
reset itself after there were low coverage failures due to some tests being removed.
This restores Cobertura to the current state.
CyberArk internal issue ID: [insert issue ID]
merged.*
changes, or
> Restore Cobertura

- Dockerfile.helm-unit-test
- helm/common/utils.sh
Fix failing build due to Helm unittest failures.
The latest version of helm-unittest, v0.3.1, fails tests that render templates with the `$.Files.Get` function. This is used by our Cluster Prep chart, so pinning until this is fixed.
This [bug](https://github.com/helm-unittest/helm-unittest/issues/135) is known and a fix is in the works.
CNJR-1231
merged.*
changes, or
> Pin helm-unittest plugin to v0.2.11

- bin/publish
Fix tagging of Redhat images.
Currently we are only publishing the version tagged image, so `latest` is never updated when new images are pushed to the RH registry
merged.*
changes, or
> Publish latest tag to Redhat on promote
